- name: install apache
  yum: name={{item}} state=present
  with_items:
   - httpd24
   - httpd24-tools
   - perl-CPAN
   - perl-Authen-PAM
   - mod24_ssl
   - perl-libwww-perl
   - perl-App-cpanminus
  notify:
   - enable apache boot
   - restart apache
  tags:
   - apache
   - webdav


#devel includes apxs, which allows authen install
- name: install devel tools
  yum: name=httpd24-devel state=present
  notify:
   - clone authenz
   - create authenz install files
   - activate authenz
   - authen cleanup
   - restart apache
  tags:
   - webdav

#Activate volume, if attached.
#This doesn't detect "mounted" specifically, for easy local environment
#replication.
- block:
  - name: stat app drive
    stat: path=/www
    register: appdrive

  - name: sym apache volume
    file:
     src: /etc/httpd/sites-available/volumes/www.conf
     dest: /etc/httpd/sites-enabled/www.conf
     state: link
    when: appdrive.stat.exists

  tags:
   - webdav
   - apache
