--- #Sets up server from ansible pull.

- name: setup server
  hosts: "{{host_name | default ('localhost')}}"
  remote_user: "{{ssh_user}}"
  become: true
  pre_tasks:
  - include: setup.yml
  roles:
   - common
   - letsencrypt
   - codedeploy
   - awslogs
   - users
   - vagrant
   - composer
   - memcached
   - mysql
   - ec2
   - cloudwatch
   - webtools
   - drupal
   - wp
   - websites
   - nginx
   - php-fpm
   - monit
   - slack
...
