site_available: /etc/nginx/sites-available
site_enabled: /etc/nginx/sites-enabled
site_log: /var/log/nginx

#This prefix is used to set the primary domain, with site_domain
sub_domain: www
#Set to nginx default if we don't have one
site_domain: _

#Other domains the server should respond to.
site_domains: []
# - dev.example.com
# - cdn.example.com

primary_domain: "{{sub_domain}}.{{site_domain}}"

drupal_level: drupal

#Crit is a little too strict for extracting fatal php errors.
log_level: error


nginx_redirect: true
#Redirect extraneous domains back to the original domain.
nginx_redirects:
- "*.{{site_domain}}"
- "{{site_domain}}"

server_root: "/var/www/html/{{site_name}}"

pool: phpcgi

s3_bucket: none
s3_dir: keys/ssl

s3_region: us-west-2

s3_keys: none

auth_dir: /var/www/auth

nginx_dest: /var/www/html
nginx_ssl: off
nginx_log: /var/log/nginx
nginx_enabled: /etc/nginx/sites-enabled
nginx_available: /etc/nginx/sites-available

nginx_secure_redirect: true

nginx_includes:
 - apps/global/cache-live.conf
 - apps/global/php-live.conf
