#This is needed for ansible to perform MySQL functions.
- name: installing mysql python
  yum: name=MySQL-python state=present
  tags:
  - mysql
  - dev
  - live
  - local

# MariaDB works better for AWS Linux 2
- name: install mysql client
  yum:
    name: mariadb
    state: present
  ignore_errors: yes
  tags:
    - mysql
    - local
    - vagrant

- block:

  # See above on MariaDB usage.
  # we probably already have a root password and corresponding /home/root/.my.cnf which shouldn't be reset.
  - name: install mysql
    yum:
      name: mariadb-server
      state: installed
    notify:
    - restart mysql
    - enable mysql boot

  tags:
  - mysql
  - local
  - vagrant

# We need these to run before proceeding.
- meta: flush_handlers

- name: set local default
  set_fact:
    mysql_pass: default

# Insecure settings for local mysql
- block:

  - name: set default password
    set_fact:
      mysql_pass: default_pass

  - name: install my cnf
    copy: src=my.cnf dest={{mysql_cnf}}

  - name: turn off mysql grant checks
    command: /bin/systemctl set-environment MYSQLD_OPTS="--skip-grant-tables"

  - name: restart mysql
    service:
      name: mysqld
      state: restarted

  # We can't use the ansible name change when grant tables are disabled.
  # So we query manually.
  - name: change root password
    command:  /bin/mysql -u root --execute="UPDATE mysql.user SET authentication_string = PASSWORD('{{mysql_root_password}}'), password_expired = 'N' WHERE User = 'root' AND Host = 'localhost';"

  - name: sql query flush
    command:  /bin/mysql -u root --execute="FLUSH PRIVILEGES;"


  - name: unset mysqld opts
    command: /bin/systemctl unset-environment MYSQLD_OPTS

  - name: restart mysql
    service:
      name: mysqld
      state: restarted

  - name: reduce mysql password requirements
    command: /bin/mysql -u root --execute="uninstall plugin validate_password;"

  # finally, set the .my.cnf for it's easy to login.
  - name: create local user cnf
    template: src=root.cnf.j2 dest=/{{ ssh_user }}/.my.cnf mode=0600
    vars:
      mycnf_user: "{{ mysql_user }}"
      mycnf_pass: "{{ mysql_pass }}"


  # finally, set the .my.cnf for it's easy to login.
  - name: create root cnf
    template: src=root.cnf.j2 dest=/root/.my.cnf mode=0600
    vars:
      mycnf_user: "{{ mysql_root_user }}"
      mycnf_pass: "{{ mysql_root_password }}"

  - name: create mysql database
    mysql_db:
      login_user: "{{ mysql_root_user }}"
      name: "{{mysql_db}}"

  - name: create mysql user
    mysql_user:
      login_user: "{{ mysql_root_user }}"
      login_password: "{{ mysql_root_password }}"
      name: "{{mysql_user}}"
      password: "{{mysql_pass}}"
      priv: '{{mysql_db}}.*:ALL'




  tags:
   - local
   - vagrant

- name: import mysql database
  mysql_db:
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    name: "{{mysql_db}}"
    state: import
    target: "{{mysql_import_dir}}/{{mysql_import_file}}"
  ignore_errors: yes
  tags:
   - mysql_import
   - local_db_import
   - wp_import



