- block:

    - name: install private key
      aws_s3:
        bucket: {{ deploy_bucket }}
        object: private.key
        dest: /var/www/ssl
        mode: get

    - name: install ssl certificate
      aws_s3:
        bucket: {{ deploy_bucket }}
        object: ssl-bundle.crt
        dest: /var/www/ssl
        mode:

    tags:
      -ssl

    when: certbot is not defined