- name: include vagrant vars
  include_vars: vagrant.yml
  tags:
   - vagrant

- stat: path=/usr/bin/drush
  register: drush
  tags:
   - drush
   - dev
   - burris_builder
   - drupal7

- name: set memcache var
  set_fact:
    memcache_prefix: "{{ site_name}}dev_"
  tags:
    - dev

- name: set memcache var
  set_fact:
    memcache_prefix: "{{ site_name }}live_"
  tags:
  - live

#This version of Drush is only used for Drupal 7, so it needs its own tag.
#For Drupal 8, Drush should be installed via composer
- name: install drush
  get_url: url=https://github.com/drush-ops/drush/releases/download/8.1.16/drush.phar dest=/usr/bin/drush mode=ugo+x
  notify:
   - initial drush run
  when: not drush.stat.exists
  tags:
   - drush

- name: alter var permissions
  file:
    path: /var/www
    mode: 0775
    owner: ec2-user
    group: burrisx
    recurse: yes
  tags:
    - live
    - dev


#Drupal 7 install
- block:

  - name: create settings directory for drupal 7
    file:
      path: "{{ site_root }}/{{site_name}}/sites/default/"
      state: directory
      mode: 0775
      owner: ec2-user
      group: burrisx

  - name: create drupal 7 settings
    template: src=drupal.settings.j2 dest={{ site_root }}/{{site_name}}/sites/default/settings.php
    vars:
     drupal_db_name: "{{db_name}}"
     drupal_db_user: "{{db_user}}"
     drupal_db_pass: "{{db_pass}}"
     drupal_db_host: "{{db_host}}"

  - name: set drupal 7 files location
    set_fact:
      drupal_files: "{{server_root}}/sites/default/files"

  tags:
    - drupal7

#Drupal 8
- block:

  - name: increase php memory for Drupal 8
    set_fact:
      php_live_memory: 512M
      php_stage_memory: 512M
      php_dev_memory: 512M

  - name: create settings directory for drupal 8
    file:
      path: "{{ site_root }}/{{site_name}}/web/sites/default/"
      state: directory
      mode: 0775
      owner: ec2-user
      group: burrisx
    tags:
      - drupal8

  - name: create drupal 8 settings
    template: src=drupal8.settings.j2 dest={{ site_root }}/{{site_name}}/web/sites/default/settings.php
    vars:
     drupal_db_name: "{{db_name}}"
     drupal_db_user: "{{db_user}}"
     drupal_db_pass: "{{db_pass}}"
     drupal_db_host: "{{db_host}}"

  - name: set drupal 8 files location
    set_fact:
      drupal_files: "{{ site_root }}/{{site_name}}/web/sites/default/files"

  - name: running composer install
    become_user: "{{ssh_user}}"
    shell: composer install --no-interaction --prefer-dist
    args:
      chdir: "{{ site_root }}/{{ site_name }}"
      creates: "/var/www/html/{{ site_name }}/vendor"
    ignore_errors: yes

  tags:
    - drupal8


- block:

  - name: create drupal private directory
    file: path=/var/www/drupal_private state=directory mode=0777

  - name: adjust mount directory
    file: path=/mnt mode=0777

  - name: create website efs root
    file: path={{efs_mount}}/{{site_name}} state=directory mode=0777

  - name: symlink files folder
    file:
      src: "{{efs_mount}}/{{efs_name}}"
      dest: "{{drupal_files}}"
      state: link
  when:
  - drupal_files is defined
  - efs_id is defined
  tags:
    - always
