
#Get certbot and try to perform a DNS challenge
- block:

  - name: check for full chain file
    stat:
      path: /etc/letsencrypt/live/{{ site_domain }}/fullchain.pem
    register: fullchain

  - name: install certbot
    yum:
      name: certbot-dns-route53
      state: installed
      enablerepo: epel

  - name: get certbot ssls for domain
    command: /usr/bin/certbot certonly -n --agree-tos --email {{ user_email }} --dns-route53 -d {{ site_domain }} -d '*.{{ site_domain }}'
    creates: "/etc/letsencrypt/live/{{site_domain}}/fullchain.pem"
    ignore_errors: yes
    register: certbot
    when:
     - site_domain != '_'
     - user_email is defined
     - fullchain.stat.exists != True
  tags:
    - ssl


#Update nginx if the above has not failed
- block:

  - name: check for full chain file
    stat:
      path: /etc/letsencrypt/live/{{ site_domain }}/fullchain.pem
    register: fullchain

  - name: check for privkey
    stat:
      path: /etc/letsencrypt/live/{{ site_domain }}/privkey.pem
    register: privkey

  - name: set ssl full chain
    set_fact:
      nginx_ssl_dir: /etc/letsencrypt/live/{{ site_domain }}
      ssl_cert: fullchain.pem
    when: fullchain.stat.exists == True
    notify: restart nginx

  - name: set ssl privkey
    set_fact:
      nginx_ssl_dir: /etc/letsencrypt/live/{{ site_domain }}
      ssl_key: privkey.pem
    when: privkey.stat.exists == True
    notify: restart nginx

  when: certbot is defined
  tags:
    - ssl
