---
- block:

  - name: install memcached
    command: /usr/bin/amazon-linux-extras install memcached1.5=latest -y

    notify:
    - enable memcached boot
    - restart memcached

  - name: start memcached
    service: name=memcached enabled=yes state=started

  tags:
   - memcached

...